### ISSUE TITLE
[sphinx] Inconsistencies in the style of quoted code

### ISSUE THREAD

**Issue by Zimmi48** [coq/coq#12185]
The theme that we use for the Sphinx manual contains:

```css
.rst-content dl:not(.docutils) code {
  font-weight: bold;
}
```

and our own `notations.css` contains (introduced by @jfehrle):

```css
.notation {
    font-weight: bold;
}
```

The consequence is that quoted code in `:n:` context is always bold, but quoted code in simple or double backticks is bold when nested in some contexts) and not bold otherwise. It would be better to be more consistent in the font-weight in all contexts.

BTW, IIUC we can decide what single backticks are bound to. Would it make sense to make them an equivalent of `:n:` and not of double backticks, given how standard the use of this context is?

In passing, another related question is what should become of `:g:`. What was its initial purpose? What use could we give it? Could it be taken advantage of in relation to #10142?

cc @cpitclaudel
