### ISSUE TITLE
Refactoring the CI scripts

### ISSUE THREAD

**Issue by SkySkimmer** [coq/coq#7151]
# why 
Currently customizing jobs in the CI scripts is done through generating these complicated env variables like EXTRA_FOO and so on. This recently led to issues in the gitlab yml, I feel like the travis yml could also be improved. Circle has less custom stuff to do, and the opam-boot system means we don't have EXTRA_OPAM, but maybe it could also benefit.

# how 
The idea is to have "feature variables" that you turn on for specific jobs in the yml, then some script builds up the EXTRA_FOO stuff from the features you use.
eg instead of
```yml
variables:
  COQIDE_PACKAGES: "..."
  COQDOC_PACKAGES: "..."
  #...

#...

build:
  <<: *build-template
  variables:
    EXTRA_CONF: "-coqide opt -with-doc yes"
    EXTRA_PACKAGES: "$COQIDE_PACKAGES $COQDOC_PACKAGES"
    EXTRA_OPAM: "$COQIDE_OPAM $COQDOC_OPAM"
    PIP_PACKAGES: "$SPHINX_PACKAGES"
```
you would have 
```yml
build:
  <<: *build-template
  variables:
    FEAT_COQIDE: "true"
    FEAT_COQDOC: "true"
```
and a script that goes
```bash
COQIDE_PACKAGES=(...)
COQDOC_PACKAGES=(...)

if [ '${FEAT_COQIDE:-false}' != false ] ; then 
  EXTRA_CONF+=(-coqide opt)
  EXTRA_PACKAGES+=$COQIDE_PACKAGES
  EXTRA_OPAM+=$COQIDE_OPAM
fi

if [ "${FEAT_COQDOC:-false}" != false ] ; then 
  ...
fi
```
You may notice that as a bonus we get to use arrays.
